config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root "home#index"
  resources :loans
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :users, through: :loans
  has_many :loans
  validates :title, presence: true, uniqueness: true
  validates :author, presence: true

  scope :available, -> { where(state: "available")}
  scope :unavailable, -> { where(state: "unavailable")}
  scope :search, -> (search) { where("title LIKE ?", "%#{search}%")}

  def available?
    state == "available"
  end

  def current_borrower
    loans.where(return_date: nil).first&.user
  end
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user, :book, presence: true
  before_create :set_borrow_date

  def set_borrow_date
    self.borrow_date = Date.today
  end

  def borrow!
    book.update_attributes(state: "unavailable")
  end

  def return!
    book.update_attributes(state: "available")
    update_attributes(return_date: Date.today)
  end

  def active?
    self.return_date.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :loans
  has_many :books, through: :loans
  validates :firstname, :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  mount_uploader :picture, PictureUploader

  scope :search, -> (search) { where("email LIKE ?", "%#{search}%")}
  scope :active, -> { where(id: Loan.all.map(&:user).map(&:id).uniq)}

  def active_loans?
    loans.where(return_date: nil).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:search]
      @books = Book.search(params[:search])
    else
      @books = Book.all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.available?
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to books_url, notice: "This book can't be destroyed because it's not available." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :summary, :state)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books_count = Book.all.count
    @available_books_count = Book.available.count
    @unavailable_books_count = Book.unavailable.count

    @users_count = User.all.count
    @active_users_count = User.active.count
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    respond_to do |format|
      if @loan.save
        @loan.borrow!
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    @loan.return!
    respond_to do |format|
      if @loan.return!
        format.html { redirect_to @loan, notice: 'Book was successfully returned' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:user_id, :book_id, :borrow_date, :return_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.active_loans?
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User can't be destroyed. Return all borrowed books then try again" }
        format.json { head :no_content }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :firstname, :lastname, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :book_summary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<%= form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Summary</th>
      <th>State</th>
      <th>Current borrower</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.summary %></td>
        <td><%= book.state %></td>
        <td> <% if book.current_borrower %>
                <%= link_to user_path(book.current_borrower) do %>
                  <%= book.current_borrower.firstname %> <%= book.current_borrower.lastname %>
                <% end %>
              <% end %>
        </td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @book.summary %>
</p>

<p>
  <strong>State:</strong>
  <%= @book.state %>
</p>

<hr/>

<% unless @book.available? %>
  <p> <strong>Current borrower :</strong>
    <%= link_to user_path(@book.current_borrower) do %>
      <%= @book.current_borrower.firstname %> <%= @book.current_borrower.lastname %>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1> Welcome to Prium Library </h1>
</br>

<h2> Books </h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Total books</th>
      <th scope="col">Available books</th>
      <th scope="col">Unavailable books</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @books_count %></td>
      <td><%= @available_books_count %></td>
      <td><%= @unavailable_books_count %></td>
    </tr>
  </tbody>
</table>

<h2> Users </h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Total users</th>
      <th scope="col">Active users</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @users_count %></td>
      <td><%= @active_users_count %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PriumLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Prium Library", root_path, class: "navbar-brand"%>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Users", users_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Loans/Returns",loans_path, class: "nav-link"%>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :firstname) %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.collection_select(:book_id, Book.available, :id, :title) %>
    <br/>
    <em> Only available books are displayed </em>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Returning  Book</h1>

<%= form_with(model: @loan, local: true) do |form| %>
<div class="actions">
  <%= form.submit "Return" %>
</div>
<% end %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Borrow date</th>
      <th>Return date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td> <%= link_to user_path(loan.user) do %>
                <%= loan.user.firstname %> <%= loan.user.lastname %>
              <% end %>
        </td>
        <td><%= loan.book.title %></td>
        <td><%= loan.borrow_date %></td>
        <td><%= loan.return_date %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if loan.active? %>
          <td><%= link_to 'Return book', edit_loan_path(loan) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @loan.user.firstname %>
</p>

<p>
  <strong>Book:</strong>
  <%= @loan.book.title %>
</p>

<p>
  <strong>Borrow date:</strong>
  <%= @loan.borrow_date %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @loan.return_date %>
</p>

<%= link_to 'Back', loans_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :user_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :user_lastname %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :user_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= form_tag users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<% if @user.picture.present? %>
  <p>
    <strong>Pictures:</strong>
      <%= image_tag(@user.picture_url) %>
  </p>
<% end %>


<hr/>

<h2> Borrowed books </h2>
<ul>
  <% @user.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

<hr/>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>